---
title: 'Data Wrangling II: Strings and Factors'
author: "Kristal Quispe"
date: "10/19/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(p8105.datasets)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

read.csv will assign charecter variables to be factors. read_csv will not make it a factor until you tell it to. 

## String manipulation

```{r}
string_vec = c("my", "name", "is", "jeff")
#string vector that has four things in it
str_detect(string_vec, "jeff")
#every fucntion in the stringer package start with str_. The str_dectet tries to detect a pattern in string variable. Str_detet is saying in my string (string_vec), find or tell me where and if the string "Jeff" exisits. 
```


```{r}
str_replace(string_vec, "m", "M")

#replace any observation with m(lc), with M (uc)
```

```{r}
string_vec = c(
  "i think we all rule for participating",
  "i think i have been caught",
  "i think this will be quite fun actually",
  "it will be fun, i think"
  )
str_detect(string_vec, "i think$")
#i think with a $, "i think$", means which of these string ends with I think. "^i think" means which string starts with I think. 
```


```{r}
string_vec = c(
  "Y'all remember Pres. HW Bush?",
  "I saw a green bush",
  "BBQ and Bushwalking at Molonglo Gorge",
  "BUSH -- LIVE IN CONCERT!!"
  )
str_detect(string_vec, "[Bb]ush")

#"[Bb]ush", is asking if the string has bush, with a capital B or lower case b, but "ush" has to be lower case.
```

```{r}
string_vec = c(
  '7th inning stretch',
  '1St half soon to begin. Texas won the toss.',
  'she is 5 feet 4 inches tall',
  '3AM - cant sleep :('
  )
str_detect(string_vec, "[0-9][a-zA-Z]")
#here you are detecting any pattern with any number from 0 to 9, followed by any two letters, lower case a-z, upper case A to upper case Z, or a combo of both. 
```


```{r}
string_vec = c(
  'Its 7:11 in the evening',
  'want to go to 7-11?',
  'my flight is AA711',
  'NetBios: scanning ip 203.167.114.66'
  )
str_detect(string_vec, "7.11")
#this string is trying to detect any 7, followed by any charcter, then 11. (any charecter is ".")
```


```{r}
string_vec = c(
  'The CI is [2, 5]',
  ':-]',
  ':-[',
  'I found the answer on pages [6-7]'
  )
str_detect(string_vec, pattern = "\\[")
#this string detect is trying to find an open square bracket. To sppecify that you are looking for teh chareceter "[" and not the begining of a range for a regular expression. Use a back slash to indicate the bracket is a charecter, and use another back slash to indicate that the back slash you just used is for a charecter backslash and not a speacial chareceter. "Search for actual bracket that is a charecter"
```

## use strings in practice

PULSE

```{r}
pulse_data = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") %>%
  janitor::clean_names() %>%
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi") %>%
  select(id, visit, everything()) %>%
  mutate(
    visit = str_replace(visit, "bl", "00m"),
    visit = fct_relevel(visit, str_c(c("00", "01", "06", "12"), "m"))) %>%
  arrange(id, visit)
```


```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"
table_marj = 
  read_html(nsduh_url) %>% 
  html_nodes(css = "table") %>% 
  .[[1]] %>%
  html_table() %>%
  slice(-1) %>%
  as_tibble()
```

```{r}
table_marj %>% 
  select(-contains("P Value")) %>% 
  pivot_longer(
    -State,
    names_to = "age_year",
    values_to = "percent"
  ) %>% 
  separate(age_year, into = c("age", "year"), sep = "\\(") %>% #this seperares age and year by an open perentecy
  mutate(
    year = str_replace(year, "\\)", ""), # detect a close perentacy and replace with nothing. 
    percent = str_replace(percent, "[a-c]$", ""), # detect a charecter of a-c, which is at the end of the string only, and replace with nothing. 
    percent = as.numeric(percent) #make perecnt numeric, before it was charecter because it included a number before
  )
```


## Factors


```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_df %>%
  mutate(name = fct_relevel(name, c("Waterhole_WA"))) %>% 
  #the relevel here moved water hole to the first place and then left the implicit albhabetical ordering to order the rest of the graphs
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```


```{r}
weather_df %>%
  mutate(name = fct_reorder(name, tmax)) %>% 
  #instead of relevel, use reorder to relevel one factor variable according to the values of this other variable on top of it. We are reordering name, based on tmax, the name associated the smalled median t max will be level 1, and the name with the next smallest median t max will be level 2. 
  ggplot(aes(x = name, y = tmax)) + 
  geom_violin(aes(fill = name), color = "blue", alpha = .5) + 
  theme(legend.position = "bottom")
```


```{r}
data("nyc_airbnb")
nyc_airbnb %>%
  filter(neighbourhood_group == "Manhattan") %>% 
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price, na.rm = TRUE)) %>% # here we are ordering neighboorhood, based on price, and sometime prices are missing so remove those missing values
  ggplot(aes(x = neighbourhood, y = price)) +
  geom_boxplot() +
  coord_flip() + # this flips x and y axis
  ylim(0, 1000) # this limits th y axis to 10000
```


what about factors and linear models ...?

```{r}
weather_df %>%
  lm(tmax ~ name, data = .)

#name vairbles here is the categorical predictor
```

```{r}
weather_df %>%
  mutate(name = forcats::fct_relevel(name, c("Waikiki_HA", "CentralPark_NY", "Waterhole_WA"))) %>% 
  lm(tmax ~ name, data = .)
```

#If you want to change the referece gourp you can use relevel to do so. 